# After changing this file, check it on:
#   http://lint.travis-ci.org/

language: c

# Run jobs on container-based infrastructure, can be overridden per job
sudo: false

matrix:
  include:

  - env:
    - PYTHON_VER='2.7'

      #  - env:
      #    - PYTHON_VER='3.6'

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - if [[ "$PYTHON_VER" == "2.7" ]]; then
        conda create -n p4env python=$PYTHON_VER psi4 psi4-dev -c psi4 -c psi4/label/dev;
    else
        conda create -q -n p4env python=$PYTHON_VER ci-psi4 psi4 numpy=1.13 matplotlib jupyter scipy pylibefp -c psi4/label/dev -c psi4;
    fi

  - source activate p4env
  - conda list

before_script:
  - python -V

script:
  - eval $(psi4 --plugin-compile)
  - make
  - psi4 examples/H8-0.1.dat
  - bash examples/test.sh

after_success:
  - echo "Successful build!"

notifications:
  email: false

